Auction/Models/Bidder.cs
using System;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using Auction.DAL;

namespace Auction.Models
{
  public class Bidder
  {
    AuctionContext db = new AuctionContext();

    public int ID { get; set; }

    [Display(Name = "Bidder Name")]
    public string BidderName { get; set; }

    //[Display(Name = "Bidder Number")]
    // public string BidderNumber { get; set; }

    [Display(Name = "Bidder Number")]
    public int BidderNumber{ get; set; }
    
    [Display(Name = "Bidder Contact 1")]
    public string BidderContact1 { get; set; }

    [Display(Name = "Bidder Contact 2")]
    public string BidderContact2 { get; set; }

    [Display(Name = "Bidder Contact 3")]
    public string BidderContact3 { get; set; }

    //public List<IndividualMultiBidderItem> MultiItems { get; set; }
  }
}

Auction/Controllers/BidderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Auction.Models;
using Auction.DAL;

namespace Auction.Controllers
{
    public class BidderController : Controller
    {
      // private ApplicationDbContext db = new ApplicationDbContext();
      
      //using LocalDB connection string and initializer for now
       private AuctionContext db = new AuctionContext();



//Index *************************************************************************************************************
        // GET: Bidder
        public ActionResult Index()
        {
            return View(db.Bidders.ToList());
        }

//Details ************************************************************************************************************
        // GET: Bidder/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bidder bidder = db.Bidders.Find(id);
            if (bidder == null)
            {
                return HttpNotFound();
            }
            return View(bidder);
        }

//Create *************************************************************************************************************
        // GET *******************************************************************************************************
        public ActionResult Create()
        {
            return View();
        }

        // POST ******************************************************************************************************
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,BidderName,BidderNumber,BidderContact1,BidderContact2,BidderContact3 ")] Bidder bidder)
        {

           
            //int newID = 0;
            int HighestNum = 99;
            bidder.BidderNumber = 99;
            if (ModelState.IsValid)
            {
                //foreach(var b in db.Bidders )   //determines what the next auto generated Id is going to be
                //    if (b.ID > newID)
                //        newID = b.ID;

            foreach(var b in db.Bidders )
            {
                if (b.BidderNumber > HighestNum)
                    HighestNum = b.BidderNumber;
            }
                bidder.BidderNumber = HighestNum + 1;


                foreach (var mi in db.MultipleBidderItems)
                {
                    var IMBI = new IndividualMultiBidderItem();
                    IMBI.Title = mi.Title;
                    IMBI.Bidder_ID = bidder.BidderNumber;
                    db.IndividualMultiBidderItems.Add(IMBI);
                }
                db.Bidders.Add(bidder);
                db.SaveChanges();

                return RedirectToAction("NewBidder", bidder);
            }
            //return RedirectToAction("Index");
          return View(bidder);
        }
//Edit ****************************************************************************************************************
        // GET*********************************************************************************************************
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bidder bidder = db.Bidders.Find(id);
            if (bidder == null)
            {
                return HttpNotFound();
            }
            return View(bidder);
        }

        // POST********************************************************************************************************
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,BidderName,BidderNumber,BidderContact1, BidderContact2, BidderContact3")] Bidder bidder)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bidder).State = EntityState.Modified;
                db.SaveChanges();
                var index = "Index#" + bidder.BidderNumber;
                return RedirectToAction(index);
            }
            return View(bidder);
        }


//Delete ***************************************************************************************************************
        // GET *********************************************************************************************************
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bidder bidder = db.Bidders.Find(id);
            if (bidder == null)
            {
                return HttpNotFound();
            }
            return View(bidder);
        }

        // POST *******************************************************************************************************
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            foreach (var i in db.IndividualMultiBidderItems)            //remove the all individualMultiBidderItems associated with this bidder ID  for ref integrety 
            {
                if (i.Bidder_ID == id)
                {
                    db.IndividualMultiBidderItems.Remove(i);
                }
            }

            Bidder bidder = db.Bidders.Find(id);
            db.Bidders.Remove(bidder);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
//NewBidder *************************************************************************************************************
        public ActionResult NewBidder( Bidder bidder)
        {

            if (bidder.ID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            if (bidder == null)
            {
                return HttpNotFound();
            }
            return View(bidder);
        }


// Dispose **************************************************************************************************************
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Auction/Views/Bidder/Create.cshtml
@model Auction.Models.Bidder

@{
    ViewBag.Title = "Create";
}



<style type="text/css">
    #center {
        margin-left: 30%;
        margin-right: 30%;
        width: 500px;
    }
</style>

<body id="BackgroundGrad1"  class="full">
    @using (Html.BeginForm("Create", "Bidder", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @*@Html.HiddenFor(model => model.ID)*@
        @*@Html.HiddenFor(model => model.MultiItems)*@
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <h2 class="CrudTitle">Add a New Bidder</h2>
    <hr />

        <table id="IndexTable">
            <tr>
                <td>
                    <h4> Bidder Name</h4>
                </td>
                <td class="TableDataIndex2">
                    @Html.EditorFor(model => model.BidderName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BidderName, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td>
                    <h4> Bidder Contact info</h4>
                    <h6>Phone or Email</h6>
                </td>
                <td class="TableDataIndex2">
                    @Html.EditorFor(model => model.BidderContact1, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BidderContact1, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td>
                    <h4> Bidder Contact info</h4>
                    <h6>Phone or Email</h6>
                </td>
                <td class="TableDataIndex2">
                    @Html.EditorFor(model => model.BidderContact2, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BidderContact2, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td>
                    <h4> Bidder Contact info</h4>
                    <h6>Phone or Email</h6>
                </td>
                <td class="TableDataIndex2">
                    @Html.EditorFor(model => model.BidderContact3, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BidderContact3, "", new { @class = "text-danger" })
                </td>

            </tr>
            <tr>
                <td colspan="2" class="TableDataIndex2">
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Add" class="btn btn-default" />
                            <input type="submit" value="Back to Forms List" onclick="location.href='@Url.Action("Index", "Forms")';return false;" class="btn btn-default" />
                        </div>
                    </div>
                </td>
            </tr>
            <tr></tr>
        </table>
        <br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
    }

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</body>

Auction/Views/Bidder/Delete.cshtml
@model Auction.Models.Bidder

@{
    ViewBag.Title = "Delete";
}
<body id="BackgroundGrad1"  class="full">
    <h2 class="CrudTitle">Delete Bidder</h2>
    <p>
        <span class="btn btn-default"> @Html.ActionLink("Back to Forms List", "Index", "Forms")</span>
    </p>

    <h3>Are you sure you want to delete this bidder?</h3>
    
    
    <div>
      
        <table class="TableDataIndex2">
            <tr>
                <td id="BidNumber2" class="TableDataIndex6">@Html.DisplayFor(model => model.BidderNumber)</td>
                <td class="TableDataIndex6"><h2>@Html.DisplayFor(model => model.BidderName)</h2></td>
                <td class ="TableDataIndex6"><h2>@Html.DisplayFor(model => model.BidderContact1)</h2></td>
                <td class="TableDataIndex6"><h2>@Html.DisplayFor(model => model.BidderContact2)</h2></td>
                <td class="TableDataIndex6"><h2>@Html.DisplayFor(model => model.BidderContact3)</h2></td>
            </tr>
        </table>


        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" />
                <input type="submit" value="Cancel" onclick="location.href='@Url.Action("Index", "Bidder")';return false;" class="btn btn-default" />
            </div>
        }
    </div>
</body>

Auction/Views/Bidder/Details.cshtml
@model Auction.Models.Bidder

@{
    ViewBag.Title = "Details";
}

<h2>Bidder Details</h2>
<p>
    <span class="btn btn-default"> @Html.ActionLink("Back to Forms List", "Index", "Forms")</span>
</p>
<div>
    
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BidderName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BidderName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BidderNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BidderNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BidderContact1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BidderContact1)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BidderContact2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BidderContact2)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BidderContact3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BidderContact3)
        </dd>



    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) 
    @*@Html.ActionLink("Back to List", "Index")*@
    <a href="http://selectpdf.com/save-as-pdf">Save as Pdf</a>
</p>

Auction/Views/Bidder/Edit.cshtml
@model Auction.Models.Bidder

@{
    ViewBag.Title = "Edit";
}
<body id="BackgroundGrad1"  class="full">
    <h2 class="CrudTitle">Edit Bidder</h2>
    <p>
        <span class="btn btn-default"> @Html.ActionLink("Back to Forms List", "Index", "Forms")</span>
    </p>
    <div id="BidNumber" class="TableDataIndex6">@Html.DisplayFor(model => model.BidderNumber)</div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @*@Html.HiddenFor(model => model.ID)*@

            @Html.HiddenFor(model => model.BidderNumber)

            <table id="IndexTable">
                <tr>
                    <td class ="TableDataIndex16">
                        <h4>Name</h4>
                    </td>
                    <td class="TableDataIndex8" colspan="3">
                        @*<div class="form-group">*@
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.BidderName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.BidderName, "", new { @class = "text-danger" })
                            </div>
                        @*</div>*@
                    </td>
                </tr>
                <tr>
                    <td class="TableDataIndex7">
                        <h4>Contact</h4>
                    </td>
                    <td class="TableDataIndex8">
                        @*<div class="form-group">*@
                            <div class="col-md-10">
                                 @Html.EditorFor(model => model.BidderContact1, new { htmlAttributes = new { @class = "form-control" } })
                                 @Html.ValidationMessageFor(model => model.BidderContact1, "", new { @class = "text-danger" })
                            </div>
                        @*</div>*@
                    </td>
                    <td class="TableDataIndex8">
                        @*<div class="form-group">*@
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.BidderContact2, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.BidderContact2, "", new { @class = "text-danger" })
                        </div>
                        @*</div>*@
                    </td>
                    <td class="TableDataIndex8">
                        @*<div class="form-group">*@
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.BidderContact3, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.BidderContact3, "", new { @class = "text-danger" })
                        </div>
                        @*</div>*@
                    </td>
                </tr>
                <tr>
                    <td colspan="4" class="TableDataIndex1">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Save" class="btn btn-default" />
                                <input type="submit" value="Cancel" onclick="location.href='@Url.Action("Index#" + Model.BidderNumber, "Bidder")';return false;" class="btn btn-default" />
                            </div>
                    </td>
                </tr>
            </table>
        </div>
    }


</body>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Auction/Views/Bidder/Index.cshtml
@model IEnumerable<Auction.Models.Bidder>

@{
    ViewBag.Title = "Index";
}
<body id="BackgroundGrad1" class="full">
    <h2 class="CrudTitle">Bidder</h2>
    <p>
        <span class="btn btn-default"> @Html.ActionLink("Back to Forms List", "Index", "Forms")</span>
    </p>

    <p id="ListButton2">
        @Html.ActionLink("Add a New Bidder", "Create")
    </p>
    <table class="table">
        <tr>
            <th class="TableDataIndex4">
                @Html.DisplayNameFor(model => model.BidderName)
            </th>
            <th class="TableDataIndex4">
                @Html.DisplayNameFor(model => model.BidderNumber)
            </th>
            <th class="TableDataIndex4">
                @Html.DisplayNameFor(model => model.BidderContact1)
            </th>
            <th class="TableDataIndex4">
                @Html.DisplayNameFor(model => model.BidderContact2)
            </th>
            <th class="TableDataIndex4">
                @Html.DisplayNameFor(model => model.BidderContact3)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a name="@Html.DisplayFor(modelItem => item.BidderNumber)"></a>
                    @Html.DisplayFor(modelItem => item.BidderName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BidderNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BidderContact1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BidderContact2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BidderContact3)
                </td>
                <td class="TableDataIndex4">
                    <table class="TableDataIndex5">
                        <tr>
                            <td class="TableDataIndex5">
                                <div class="ButtonDiv1">@Html.ActionLink("Edit", "Edit", new { id = item.ID }) </div>
                            </td>
                            <td class="TableDataIndex5">
                                <div class="ButtonDiv1">@Html.ActionLink("Delete", "Delete", new { id = item.ID }) </div>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        }

    </table>
</body>

Auction/Views/Bidder/NewBidder.cshtml
@model Auction.Models.Bidder
@{
    ViewBag.Title = "NewBidder";
}
<body id="BackgroundGrad1"  class="full">
    <table id="IndexTable">
        <tr>
            <td>
                <h3 class="CrudTitle">New Bidder</h3>
            </td>
        </tr>
        <tr>
            <td>
                <h1> @Model.BidderName</h1>
            </td>
        </tr>
        <tr>
            <td>
                <h1 id="BidNumber"><b> @Model.BidderNumber</b></h1>
            </td>
        </tr>
        <tr>
            <td>
                <h2 id="ListButton"><a href="@Url.Action("Create", "Bidder")"><b>Add Another Bidder</b></a></h2>
            </td>
        </tr>
        <tr>
            <td>
                <h2 id="ListButton"><a href="@Url.Action("Index", "Forms")"><b>Back to Auction Forms</b></a></h2>
                @*<input type="button" value="Add Another Bidder" onclick="location.href='@Url.Action("Create", "Bidder")';return false;" class="btn btn-default" />*@
            </td>
        </tr>
    </table>
    
   
    
</body>