Auction/Controllers/DonorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Auction.DAL;
using Auction.Models;

namespace Auction.Controllers
{
    public class DonorController : Controller
    {
        private AuctionContext db = new AuctionContext();

        // GET: Donor
        public ActionResult Index()
        {
            return View(db.Donors.ToList());
        }

        // GET: Donor/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Donor donor = db.Donors.Find(id);
            if (donor == null)
            {
                return HttpNotFound();
            }
            return View(donor);
        }

        // GET: Donor/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Donor/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Email,Phone,Address,City,State,Zip,Items,Value")] Donor donor)
        {
            if (ModelState.IsValid)
            {
                db.Donors.Add(donor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(donor);
        }

        // GET: Donor/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Donor donor = db.Donors.Find(id);
            if (donor == null)
            {
                return HttpNotFound();
            }
            return View(donor);
        }

        // POST: Donor/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Email,Phone,Address,City,State,Zip,Items,Value")] Donor donor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(donor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(donor);
        }

        // GET: Donor/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Donor donor = db.Donors.Find(id);
            if (donor == null)
            {
                return HttpNotFound();
            }
            return View(donor);
        }

        // POST: Donor/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Donor donor = db.Donors.Find(id);
            db.Donors.Remove(donor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Auction/Controllers/HelpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Auction.Controllers
{
  
    public class HelpController : Controller
    {
        // GET: Help
        public ActionResult Index()
        {
            return View();
        }
    }
}

Auction/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using Auction.Models;
using Auction.DAL;

namespace Auction.Controllers
{

  public class ItemController : Controller
  {
    //private ApplicationDbContext db = new ApplicationDbContext();

    //using LocalDB connection string and initializer for now
    private AuctionContext db = new AuctionContext();


    //Index **********************************************************************************************************
    public ActionResult Index()
    {
      return View(db.Items.ToList());
    }

    //Details ********************************************************************************************************
    // GET: Item/Details/5
    public ActionResult Details(int? id)
    {
      if (id == null)
      {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Item item = db.Items.Find(id);
      if (item == null)
      {
        return HttpNotFound();
      }
      return View(item);
    }


    //Create *********************************************************************************************************
    // GET****************************************************************************************************
    public ActionResult Create()
    {
      return View();
    }

    // POST:**************************************************************************************************
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create(
        [Bind(Include = "ID,Title,Description,ImageURL,AuctionType,WinningBidder,BidAmount")] Item item,
        string image,
    HttpPostedFileBase photo)
    {
      var path = HttpContext.Server.MapPath("~/Images/Items/" + image);

      path = path.Replace(" ", string.Empty);
      path.Trim();

      if (photo != null)
        photo.SaveAs(path);

      // orriginal code
      int HighestNum = 0;
      item.ItemNumber = 0;
      if (ModelState.IsValid)
      {
        foreach (var i in db.Items)
        {
          if (i.ItemNumber > HighestNum)
            HighestNum = i.ItemNumber;
        }
        item.ItemNumber = HighestNum + 1;
        db.Items.Add(item);
        db.SaveChanges();
        return RedirectToAction("Index");
      }

      return View(item);
    }


    //EDIT ************************************************************************************************************
    // GET ****************************************************************************************************
    public ActionResult Edit(int? id)
    {
      string sess = (string)System.Web.HttpContext.Current.Session["blah"];
      if (id == null)
      {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Item item = db.Items.Find(id);
      if (item == null)
      {
        return HttpNotFound();
      }
      return View(item);
    }

    // POST ****************************************************************************************************
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit([Bind(Include = "ID,ItemNumber,Title,Description,ImageURL,AuctionType,WinningBidder,BidAmount")] Item item
        , string image,
    HttpPostedFileBase photo)
    {
      
      //bool bidderIsError = true;    //Flag to check for a valid bidder
     
      var bidderIsError = true;    //Flag to check for a valid bidder

      var title = HttpContext.Server.MapPath("~/Images/Items/" + item.Title.Replace(" ", string.Empty) + ".jpg");
      var path = HttpContext.Server.MapPath("~/Images/Items/" + image);

      if (path != title)
        System.IO.File.Move(path, title);
     
      //string path = HttpContext.Server.MapPath("~/Images/Items/" + image);

      if (photo != null)
        photo.SaveAs(path);
      // orriginal code
      if (ModelState.IsValid)
      {
        foreach (var b in db.Bidders)
          if (b.BidderNumber == item.WinningBidder || item.WinningBidder == null)
            bidderIsError = false;

        if (bidderIsError)
          item.WinningBidder = null;

        db.Entry(item).State = EntityState.Modified;
        db.SaveChanges();
        var index = "Index#" + item.ItemNumber;
        return RedirectToAction(index);
      }

      return View(item);
    }


    //Delete *****************************************************************************************************************************
    // GET ***********************************************************************************************************************
    public ActionResult Delete(int? id)
    {
      if (id == null)
      {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Item item = db.Items.Find(id);
      if (item == null)
      {
        return HttpNotFound();
      }
      return View(item);
    }

    // POST ************************************************************************************************************************
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public ActionResult DeleteConfirmed(int id, string photoFileName)
    {
      Item item = db.Items.Find(id);




      var photoName = "";
      photoName = item.ImageURL;
      string fullPath = Request.MapPath("~/Images/Items/"
      + photoName);

      if (System.IO.File.Exists(fullPath))
      {
        System.IO.File.Delete(fullPath);

      }


      db.Items.Remove(item);
      db.SaveChanges();
      return RedirectToAction("Index");
    }






    //Image upload and delete code
    //Do not delete
    //
    //
    //
    [HttpPost]
    public ActionResult DeletePhoto(string photoFileName)
    {
      var photoName = "";
      photoName = photoFileName;
      string fullPath = Request.MapPath("~/Images/Items/"
      + photoName);

      if (System.IO.File.Exists(fullPath))
      {
        System.IO.File.Delete(fullPath);

      } return RedirectToAction("Index");
    }
    //
    //
    //
    //Do not delete
    //Image upload and delete code



    protected override void Dispose(bool disposing)
    {
      if (disposing)
      {
        db.Dispose();
      }
      base.Dispose(disposing);
    }
  }
}

Auction/Views/Forms/AddMultiItemBids.cshtml
@model Auction.ViewModels.MultiBidderItemVM

@{
    ViewBag.Title = "Add Extra auction Bids";
}

<body id="BackgroundGrad1" class="full">

    <h1 class="CrudTitle">@Html.DisplayFor(modelItem => Model.Title)</h1>
    <p>
        <span class="btn btn-default"> @Html.ActionLink("Back to Forms List", "Index", "Forms")</span>
    </p>
    <h2 id="Theme">Enter bid amounts for each bidder </h2>
    @using (Html.BeginForm("AddMultiItembids", "Forms", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <table class="table" id="IndexTable">
            @foreach (var item in Model.IMBIList)
            {

                <tr>
                    @if (item.BidAmount == null || item.BidAmount < 1)
                    {
                        <td class="TableDataIndex17">
                            <h3 style="color:darkred"><b>@Html.DisplayFor(modelItem => item.Bidder_ID)</b></h3>
                        </td>
                    }
                    else
                    {
                        <td class="TableDataIndex17">
                            <h3><b>@Html.DisplayFor(modelItem => item.Bidder_ID)</b></h3>
                        </td>
                    }
              

                    @if (item.BidAmount == null || item.BidAmount < 1)
                    {
                        <td class="TableDataIndex17">
                            <div class="col-md-10">
                                @*@Html.EditorFor(modelItem => item.BidAmount, new { htmlAttributes = new { @class = "form-control", @id = item.ID } })
                                    @Html.ValidationMessageFor(modelItem => item.BidAmount, "", new { @class = "text-danger" })*@
                            </div>
                        </td>
                    }
                    else
                    {
                        <td class="TableDataIndex17">
                            <h3>@Html.DisplayFor(modelItem => item.BidAmount)</h3>
                        </td>
                    }



                    <td class="TableDataIndex18">
                        @if (item.BidAmount == null || item.BidAmount == 0)
                        {



                            @Html.HiddenFor(modelItem => item.Bidder_ID, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(modelItem => item.Bidder_ID, "", new { @class = "text-danger" })
                            @Html.HiddenFor(modelItem => item.Title, new { htmlAttributes = new { @class = "form-control", } })
                            @Html.ValidationMessageFor(modelItem => item.Title, "", new { @class = "text-danger" })
                            @Html.HiddenFor(modelItem => item.ID, new { htmlAttributes = new { @class = "form-control", } })
                            @Html.ValidationMessageFor(modelItem => item.ID, "", new { @class = "text-danger" })

    <table class="TableDataIndex5">
        <tr>
            <td class="TableDataIndex19">
                <div class="ButtonDiv1" style="color:darkred">@Html.ActionLink("Load", "EditIndividualMultiBidderItem", new { id = item.ID }) </div>
            </td>

        </tr>
    </table>
                        }
                        else
                        {
                            @*<div class="ButtonDiv1"> @Html.ActionLink("Edit", "EditLiveItem", new { id = item.ID }) </div>*@
                            <table class="TableDataIndex5">
                                <tr>
                                    <td class="TableDataIndex19">
                                        <div class="ButtonDiv1">@Html.ActionLink("Edit", "EditIndividualMultiBidderItem", new { id = item.ID }) </div>
                                    </td>

                                </tr>
                            </table>
                        }
                    </td>
                </tr>
            }

        </table>
    }
</body>

Auction/Views/Forms/AddMultiItemsList.cshtml
@model IEnumerable<Auction.Models.MultipleBidderItem>
@{
    ViewBag.Title = "AddMultiItemsList";
}

<body id="BackgroundGrad1"  class="full">
    <table id="IndexTable">
        <tr>
            <td colspan="2">
                <h1 class="CrudTitle">Load Bids for:</h1>
                <br />
            </td>
        </tr>

        @foreach (var mi in Model)
        {
            <tr>
                <td>
                    <h4 id="ListButton"><a href="@Url.Action("AddMultiItemBids", "Forms" , new { mi.Title })"><b>@Html.DisplayFor(modelItem => mi.Title) </b></a></h4>
                </td>
            </tr>

        }

    </table>
</body>

Auction/Views/Forms/AddWinningBids.cshtml
@model IEnumerable<Auction.Models.Item>
@{
    ViewBag.Title = "AddWinningBids";
}

<h2>AddWinningBids</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImageURL)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AuctionType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WinningBidder)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BidAmount)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AuctionType)
            </td>
            @*<td>
                <div class="form-group">
                    @Html.LabelFor(model => model.BidAmount, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.BidAmount, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.BidAmount, "", new { @class = "text-danger" })
                    </div>
                </div>
            </td>
            <td>
                <div class="form-group">
                    @Html.LabelFor(model => model.WinningBidder, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.WinningBidder, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.WinningBidder, "", new { @class = "text-danger" })
                    </div>
                </div>
            </td>*@
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>

Auction/Views/Forms/AddWinningBidsLive.cshtml
@model List<Auction.Models.Item>
@{
    ViewBag.Title = "AddWinningBidsLive";
}

<body id="BackgroundGrad1" class="full">

    <h1 class="CrudTitle">Live Auction</h1>
    <p>
        <span class="btn btn-default"> @Html.ActionLink("Back to Forms List", "Index", "Forms")</span>
    </p>
    <h2 id="Theme">Enter Winning Bids</h2>
    @using (Html.BeginForm("AddWinningBidsLive", "Forms", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
       

        <table class="table" id="IndexTable">
            <tr>
                <td>
                    <h4>Number</h4>
                </td>
                <td colspan="2">
                    <h4>Item</h4>
                </td>
                @*<td>
                        <h4>Description</h4>
                    </td>*@
                <td>
                    <h4>Winning Bidder #</h4>
                </td>
                <td>
                    <h4>Bid Amount</h4>
                </td>
                <td></td>
            </tr>

            @foreach (var item in Model)
            {

                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ID)
                    </td>
                    <td colspan="2">
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    @*<td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>*@


                    @if (item.WinningBidder == null || item.WinningBidder == 0)
                    {
                        <td>
                            <div class="col-md-10">
                                @*@Html.EditorFor(modelItem => item.WinningBidder, new { htmlAttributes = new { @class = "form-control", @id = item.ID } })
                                @Html.ValidationMessageFor(modelItem => item.WinningBidder, "", new { @class = "text-danger" })*@
                            </div>
                        </td>
                    }
                    else
                    {
                        <td>
                            @Html.DisplayFor(modelItem => item.WinningBidder)
                        </td>
                    }

                    @if (item.BidAmount == null || item.BidAmount == 0)
                    {
                        <td>
                            <div class="col-md-10">
                                @*@Html.EditorFor(modelItem => item.BidAmount, new { htmlAttributes = new { @class = "form-control", @id = item.ID } })
                                @Html.ValidationMessageFor(modelItem => item.BidAmount, "", new { @class = "text-danger" })*@
                            </div>
                        </td>

                    }
                    else
                    {
                        <td>
                            @Html.DisplayFor(modelItem => item.BidAmount)
                        </td>
                    }

                    <td>
                        @if ((item.BidAmount == null || item.BidAmount == 0) && (item.WinningBidder == null || item.WinningBidder == 0))
                        {
                            @*<div> Submit button </div>*@


                            @Html.HiddenFor(modelItem => item.AuctionType, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(modelItem => item.AuctionType, "", new { @class = "text-danger" })

                            @Html.HiddenFor(modelItem => item.ID, new { htmlAttributes = new { @class = "form-control", } })
                            @Html.ValidationMessageFor(modelItem => item.ID, "", new { @class = "text-danger" })
                            @Html.HiddenFor(modelItem => item.Title, new { htmlAttributes = new { @class = "form-control", } })
                            @Html.ValidationMessageFor(modelItem => item.Title, "", new { @class = "text-danger" })
                            @Html.HiddenFor(modelItem => item.Description, new { htmlAttributes = new { @class = "form-control", } })
                            @Html.ValidationMessageFor(modelItem => item.Description, "", new { @class = "text-danger" })
                            @Html.HiddenFor(modelItem => item.ItemNumber, new { htmlAttributes = new { @class = "form-control", } })
                            @Html.ValidationMessageFor(modelItem => item.ItemNumber, "", new { @class = "text-danger" })
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    @*<input type="submit" value="Save" class="btn btn-default" id=@item.ID />*@
                                    <div class="ButtonDiv1"> @Html.ActionLink("Load", "EditLiveItem", new { id = item.ID }) </div>
                                </div>
                            </div>
                        }
                        else
                        {
                            <div class="ButtonDiv1"> @Html.ActionLink("Edit", "EditLiveItem", new { id = item.ID }) </div>
                        }
                    </td>
                </tr>
            }

        </table>
    }
</body>

Auction/Views/Forms/EditIndividualMultiBidderItem.cshtml
@model Auction.Models.IndividualMultiBidderItem

@{
    ViewBag.Title = "Edit IndividualMultiBidderItem";
}

<style>
    footer {
        position: absolute;
        bottom: 0;
        width: 80%;
    }
</style>

<body id="BackgroundGrad1" class="full">
    <hgroup class="title">
        <h1 class="CrudTitle"> @Model.Title bid @*for Bidder <span style="color:darkred">@Model.Bidder_ID</span>*@</h1>
        
    </hgroup>
    <p>
        <span class="btn btn-default"> @Html.ActionLink("Back to Forms List", "Index", "Forms")</span>
    </p>
    @using (Html.BeginForm("EditIndividualMultiBidderItem", "Forms", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.Bidder_ID)
        @Html.HiddenFor(model => model.Title)


        <table id="IndexTable" @*class="TableDataIndex2 TableIndex2"*@>
            <tr>
                <td>
                    <h4><b>Bidder</b></h4>
                </td>
                <td>
                    <h4><b>Bid Amount</b></h4>
                </td>
            </tr>
            <tr>
                <td class="TableDataIndex7">
                    @*@Html.LabelFor(model => model.BidAmount, htmlAttributes: new { @class = "control-label col-md-2" })*@
                    <h2 Class="CrudTitle" style="color:darkred"> @Model.Bidder_ID</h2>
                </td>
                <td class="TableDataIndex8">
                    <div class="form-group">
                        <div class="col-md-10" >
                            @Html.EditorFor(model => model.BidAmount, new { htmlAttributes = new { @class = "form-control"} })
                            @Html.ValidationMessageFor(model => model.BidAmount, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>

                <td colspan="2">
                    <input type="submit" value="Save" class="btn btn-default" />
                </td>
            </tr>
        </table>
    }
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

</body>

Auction/Views/Forms/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<body id="BackgroundGrad1"  class="full">

    <table id="IndexTable">
        <tr>
            <td colspan="3">
                <h1 class="CrudTitle">Auction Forms</h1>
                <br />
            </td>
        </tr>
        <tr>
            <td>
                <h3 class="formItem"> Bidders</h3>
            </td>
            <td>
                <h4 id="ListButton"><a href="@Url.Action("Create", "Bidder")"><b>Add </b></a></h4>
                <h4 id="ListButton"><a href="@Url.Action("index", "Bidder")"><b>Edit </b></a></h4>
            </td>
            <td class="TableDataIndex15">
                <h5><u>Bidder</u>: Auction participant who will use their assigned <i>Bidder Number</i> to bid on auction items. This may be an individual, couple or family.</h5>
            </td>
        </tr>
        <tr>
            <td>
                <h3 class="formItem"> Auction Items</h3>
            </td>
            <td>
                <h4 id="ListButton"><a href="@Url.Action("Create", "Item")"><b>Add</b></a></h4>
                <h4 id="ListButton"><a href="@Url.Action("Index", "Item")"><b>Edit </b></a></h4>
            </td>
            <td class="TableDataIndex15">
                <h5><u>Auction Item</u>: Items or services that will be available to be bid on, in both the live auction or the silent auction.</h5>
            </td>
        </tr>
        <tr>
            <td>
                <h3 class="formItem"> Extra Auction Items </h3>
            </td>
            <td>
                <h4 id="ListButton"><a href="@Url.Action("Create", "MultipleBidderItem")"><b>Add</b></a></h4>
                <h4 id="ListButton"><a href="@Url.Action("Index", "MultipleBidderItem")"><b>Edit </b></a></h4>
            </td>
            <td class="TableDataIndex15">
                <h5><u>Extra Auction Item</u>: An item such as a raffle, cash donation or dessert dash, that all bidders have an opportunity to give towards.</h5>
            </td>
        </tr>
        <tr>
            <td>
                <h3 class="formItem"> Donors </h3>
            </td>
            <td>
                <h4 id="ListButton"><a href="@Url.Action("Create", "Donor")"><b>Add</b></a></h4>
                <h4 id="ListButton"><a href="@Url.Action("Index", "Donor")"><b>Edit </b></a></h4>
            </td>
            <td class="TableDataIndex15">
                <h5><u>Donor</u>: Person, family or business that has donated items or services to the Auction.</h5>
            </td>
        </tr>
        <tr>
            <td>
                <h3 class="formItem"> Enter Winning Bids </h3>
            </td>
            <td>
                <h4 id="ListButton"><a href="@Url.Action("AddWinningBidsSilent", "Forms")"><b>Silent Auction </b></a></h4>
                <h4 id="ListButton"><a href="@Url.Action("AddWinningBidsLive", "Forms")"><b>Live Auction </b></a></h4>
                <h4 id="ListButton"><a href="@Url.Action("AddMultiItemsList", "Forms")"><b>Extra Auction Items </b></a></h4>
            </td>
            <td class="TableDataIndex15">
                <h5> Enter the winning bid amounts after a particular auction has closed.</h5>
            </td>
        </tr>
        <tr>
            <td>
                <h3 class="formItem"> Auction Info </h3>
            </td>
            <td>
                <h4 id="ListButton"><a href="@Url.Action("Edit", "AuctionDetail", new { id = 1 })"><b>Edit Auction Details </b></a></h4>
                <h4 id="ListButton"><a href="@Url.Action("Edit", "Contact", new { id = 1 })"><b>Edit Contact Info </b></a></h4>
                <h4 id="ListButton"><a href="@Url.Action("Edit", "Tickets", new { id = 1 })"><b>Edit Ticket Sales</b></a></h4>
            </td>
            <td class="TableDataIndex15">
                <h5>Update the auction details shown on the Auction Home page.<br /> <br /><br /></h5>

                <h5>Update the Contact information shown at the bottom of certian pages. <br /><br /></h5>

                <h5>Update information pertaining to ticket sales, for use in Auction Reports.</h5>
            </td>
        </tr>
     
        <tr>
            <td>
                <h3 class="formItem">Help </h3>
            </td>
            <td>
                <h4 id="ListButton"><a href="@Url.Action("Index", "Help")"><b>Help</b></a></h4>
            </td>
            <td class="TableDataIndex15">
                <h5>Get help on a particular area of the auction website.</h5>
            </td>
        </tr>
        <tr>
            <td>
                <h3 class="formItem" > Delete Auction </h3>
            </td>
            <td>
                <h4 id="ListButton"> <a href="@Url.Action("Delete", "ResetAuction", new { id = 1 })"><b style ="color:red">Clear the Database</b></a></h4>
            </td>
            <td class="TableDataIndex15">
                <h5>This option will clear all the auction data from the Database to start a new auction.</h5>
            </td>
        </tr>
    </table>

</body>
 